### ISSUE TITLE
Sorting by Order in Multiple Ways

### ISSUE THREAD

**Issue by ProfessorManhattan** [ota-meshi/eslint-plugin-jsonc#129]
Hey, I'm trying to get this plugin to put the name in package.json first, then version second, and then after that everything alphabetically... is it possible to use two sort methods at the same time like this?

**Comment by ota-meshi** [comment]
Now the plugin doesn't have a way to do that. We need to add a new option to the sort-keys rule.

**Comment by ProfessorManhattan** [comment]
thanks @ota-meshi -- maybe I'll open a PR... is this something you want to add to the project?

**Comment by ota-meshi** [comment]
> you want to add to the project?

Yes. I think it's good to add options to the rules. However, we need to consider what format options to add.

**Comment by ProfessorManhattan** [comment]
Hey @ota-meshi -- any ideas on what you want to name the keys? Also, how does the selector path work? What would be the selector for something like this:

```
{
  "myArray": [
    {
      "mySecondArray": [
         {
            "xyz": "test_data",
            "abc": "abc"
         }
      ]
    }
  ]
}
```

Where I want to sort the inner object's keys alphabetically.

**Comment by ota-meshi** [comment]
My first idea is to accept nested options.

```json
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$", // Hits the root properties
            "order": [
                "name",
                "version",
                "private",
                "publishConfig",
                // Nesting
                {
                    "keyPattern": "^[\\s\\S]*$", // All keys
                    "order": { "type": "asc" }
                },
            ]
        }
    ]
}
```

The second idea is to add an order for fallback as an option.

```json
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$",
            "order": [
                "name",
                "version",
                "private",
                "publishConfig"
            ],
            "fallbackOrder": { "type": "asc" } // Order if there is no matching key.
        }
    ]
}
```

I think the first idea option is more flexible and allows you to do more, but it also seems a bit more difficult to set up.

**Comment by DEPHi3** [comment]
> Where I want to sort the inner object's keys alphabetically.

Something like this was working for me
"pathPattern": "mySecondArray[\\[].*[\\]]$"

**Comment by DEPHi3** [comment]
I like the second option (in my case I do not know names of all properties, so it is difficult to make a pattern).

Additionally it could be really useful to have an option to define an absolute position (to be able to check that something is first or last).

Or maybe some "null" placeholder (some keyword) in the order array - this could mean that nothing can be placed in that position. E.g. if placed before "name", then the "name" must be first etc.

**Comment by ota-meshi** [comment]
> Additionally it could be really useful to have an option to define an absolute position (to be able to check that something is first or last).

The second option can't do that.
The first option can do that.

```jsonc
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$",
            "order": [
                "name",
                "version",
                "private",
                "publishConfig",
                {
                    "keyPattern": "^[\\s\\S]*$",
                    "order": { "type": "asc" }
                },
                "keepLast"
            ]
        }
    ]
}
```

>  (in my case I do not know names of all properties, so it is difficult to make a pattern).

What do you think if make keyPattern optional so that it matches all properties if omitted?


```jsonc
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$",
            "order": [
                "name",
                "version",
                "private",
                "publishConfig",
                {
                    "order": { "type": "asc" }
                },
                "keepLast"
            ]
        }
    ]
}
```

**Comment by DEPHi3** [comment]
AFAIK the current implementation allows some "undefined" keys between "defined" keys in the order array (e.g. there can be "something", between "name" and "version"). If nothing is allowed between specific keys and all optional keys must be defined by a nested ordering with optional pattern, it could fulfill all requirements. So option 1 with optional key patterns and unknown keys prohibited between fixed keys.

**Comment by ota-meshi** [comment]
Sorry, I wasn't sure what you were worried about. Could you explain again using JSON code?

**Comment by DEPHi3** [comment]
I mean when we use this config
```
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$",
            "order": [
                "name",
                "version",
                "private",
                "publishConfig",
                {
                    "order": { "type": "asc" }
                },
                "keepLast"
            ]
        }
    ]
}
```
then this structure would be invalid
```
{
    "name": "valid element",
    "invalid": "invalid element because nothing can be placed between name and version",
    "version": "valid element",
    "private": "valid element",
    "abc": "valid alphabetical (allowed by nested order type ASC)",
    "ghi": "valid alphabetical (allowed by nested order type ASC)",
    "def": "invalid alphabetical (out of ASC order)",
    "keepLast": "valid element",
    "invalid": "invalid element because nothing is allowed after keepLast"
}
```
but this could be tricky, because e.g. you need to know if "keepLast" is checked by the fixed key in the "fixed" order array or by the nested alphabetical ASC order.
It gets even worse when you allow multiple nested order definitions like this
```
{
    "jsonc/sort-keys": ["error",
        {
            "pathPattern": "^$",
            "order": [
                "alwaysFirst",
                {
                    "keyPattern": "<some pattern for non-numeric elements>",
                    "order": { "type": "asc" }
                },
                {
                    "keyPattern": "<some pattern for numeric elements>",
                    "order": { "type": "asc" }
                },
                "alwaysLast"
            ]
        }
    ]
}
```
with such config this should be a valid structure

```
{
    "alwaysFirst": "first element",
    "A": "non-numeric alphabetical",
    "B": "non-numeric alphabetical",
    "C": "non-numeric alphabetical",
    "1": "numeric alphabetical",
    "2": "numeric alphabetical",
    "3": "numeric alphabetical",
    "alwaysLast": "last element"
}
```

**Comment by ota-meshi** [comment]
Thank you for your explanation.

> but this could be tricky, because e.g. you need to know if "keepLast" is checked by the fixed key in the "fixed" order array or by the nested alphabetical ASC order.

I think it works as the user intended by using the order in preference to the fixed order definition over the nested order definition.

```json
"order": [
    "name", // <- check #1
    "version", // <- check #2
    "private", // <- check #3
    "publishConfig", // <- check #4
    {
        "order": { "type": "asc" } // <- check #6
    },
    "keepLast" // <- check #5
]
```

> It gets even worse when you allow multiple nested order definitions like this

If it works as I said earlier, non-numeric and numeric can be defined as:

```json
"order": [
    "alwaysFirst",
    {
        "keyPattern": "[^0-9]+",
        "order": { "type": "asc" }
    },
    {
        "keyPattern": "[0-9]+",
        "order": { "type": "asc" }
    },
    "alwaysLast"
]
```

However, multiple nesting is complicated. So I'm not sure if the user can use it well.
I think it may be necessary to add new options in some cases. But in the first place, I don't know if users want such a complicated sort.
