### ISSUE TITLE
Enable the appropriate recommended config according to the extension

### ISSUE THREAD

**Issue by kecrily** [ota-meshi/eslint-plugin-jsonc#168]
I read the code but didn't get it.

If I use the recommended configuration for `.json`, `.jsonc` and `.json5` at the same time, will it automatically use the appropriate configuration based on the file extension?

If not, what do I have to do to get them to use the appropriate configuration based on the extension.

**Comment by politician** [comment]
This should totally be added in the docs!

I was about to open an issue.

**Comment by ota-meshi** [comment]
Please open the pull request.

**Comment by politician** [comment]
https://github.com/ota-meshi/eslint-plugin-jsonc/pull/175
