### ISSUE TITLE
Unexpected `Strings must use singlequote` error on `jsonc/auto` rule?

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-jsonc#178]
````md
```json
{
  "plugins": [
    "preset-lint-consistent",
    "preset-lint-recommended",
    "preset-lint-markdown-style-guide",
    "preset-prettier"
  ]
}
```
````

JSON in markdown, parsed by [eslint-mdx](https://github.com/mdx-js/eslint-mdx) with `mdx/code-blocks` setting enabled.

My related eslint config: https://github.com/1stG/configs/blob/master/packages/eslint-config/overrides.js#L490-L513 and prettier-config: https://github.com/1stG/configs/blob/master/packages/prettier-config/base.js

It is processed as `x.md/0_x.json` as virtual filename.

**Comment by JounQin** [comment]
https://github.com/ota-meshi/eslint-plugin-jsonc/blob/3e2351da1ede4659c6695e25728f0d0f436adacd/lib/utils/get-auto-jsonc-rules-config.ts#L87

related codes, virtual filenames should be considered, there is a `context.getPhysicalFilename()` API get the filename directly.

I'm going to work on a fix if w agree with above.

@ota-meshi

**Comment by JounQin** [comment]
https://github.com/ota-meshi/eslint-plugin-jsonc/blob/3e2351da1ede4659c6695e25728f0d0f436adacd/lib/utils/get-auto-jsonc-rules-config.ts#L87

related codes, virtual filenames should be considered, there is a `context.getPhysicalFilename()` API get the filename directly.

I'm going to work on a fix if w agree with above.

@ota-meshi

**Comment by JounQin** [comment]
https://github.com/ota-meshi/eslint-plugin-jsonc/blob/3e2351da1ede4659c6695e25728f0d0f436adacd/lib/utils/get-auto-jsonc-rules-config.ts#L87

related codes, virtual filenames should be considered, there is a `context.getPhysicalFilename()` API get the filename directly.

I'm going to work on a fix if w agree with above.

@ota-meshi

**Comment by JounQin** [comment]
And also, `jsonc/auto` seems can not be disabled once enabled, if true, it should be documented because this behavior is definitely unsafe.

**Comment by ota-meshi** [comment]
I haven't yet identified the cause of this issue. I'm having a hard time reproducing the problem. Can you provide a reproducible repository?

**Comment by ota-meshi** [comment]
> related codes, virtual filenames should be considered, there is a context.getPhysicalFilename() API get the filename directly, and when a virtual filename is being used, it should be used to resolve ESLint config directly.

I think we probably can't use `getPhysicalFilename()` because we need to get the configuration of `*.json` 🤔

**Comment by JounQin** [comment]
https://github.com/1stG/configs/tree/repro/jsonc

Here we go.

```sh
# branch repro/jsonc

yarn && yarn eslint README.md
```

**Comment by JounQin** [comment]
> And, `jsonc/auto` seems can not be disabled once enabled, if true, it should be documented because this behavior is definitely unsafe.
> 
> Also, it is using another `ESLint` `CLIEngine` inside on every single call, this would affect the performance implicitly, this should also be documented. This rule should be discouraged IMO.

@ota-meshi What do you think about these comments?

**Comment by ota-meshi** [comment]
CLIEngine is used only when using eslint v6 together, so I think it's okay if we drop supporting eslint v6.
What do you think?

**Comment by ota-meshi** [comment]
Also, the part where wanted to use getPhysicalFilename is the code used in eslint v6, so getPhysicalFilename does not exist yet.

**Comment by JounQin** [comment]
> And, jsonc/auto seems can not be disabled once enabled

I'm not sure if it is true, when I met this bug I tried to disable rule `jsonc/auto` but failed.

For other ESLint versions, `new eslintrc.Legacy.CascadingConfigArrayFactory()` is used, right? The `Legacy` symbol indicates we should rely on it? And still, it will resolve configs for every single file, right?

**Comment by ota-meshi** [comment]
> > And, jsonc/auto seems can not be disabled once enabled

Hmm. I can't reproduce it. If the issue remains and you can reproduce the issue, could you share the detailed steps to reproduce it?

> The Legacy symbol indicates we should rely on it?

The ESLint team plans to implement a new configuration file format. That's why, I think the current configuration format is called Legacy. However, I have not confirmed it, so it may be wrong.

**Comment by ota-meshi** [comment]
I found a document explaining it.
https://github.com/eslint/eslintrc#future-usage
