### ISSUE TITLE
`no-irregular-whitespace` gets reported in strings

### ISSUE THREAD

**Issue by privatenumber** [ota-meshi/eslint-plugin-jsonc#197]
[`no-irregular-whitespace`](https://eslint.org/docs/latest/rules/no-irregular-whitespace) gets reported even when the irregular whitespace is in a string.

The default option should ignore strings:
> `"skipStrings": true` (default) allows any whitespace characters in string literals

## Reproduction
https://ota-meshi.github.io/eslint-plugin-jsonc/playground/#eJyrVkrOT0lVslKqjslTAIIYpbT8/BglKyDj0IIYpZi8WqVaAMnkC1o=

**Comment by ota-meshi** [comment]
Thank you for reporting the issue!
I think we need to add a new extension rule for JSONC in this plugin.
