### ISSUE TITLE
Adding no-duplicate-values-in-json files rule feature to the plugin

### ISSUE THREAD

**Issue by turturmurmur** [ota-meshi/eslint-plugin-jsonc#210]
Hi there,
I have been searching for a no duplicate values in a json file (not keys, but values) rule or plugin. I believe it can be beneficial. I have written the logic myself already but have problems when it integrates to eslint. I could collaborate and add that feature to this plugin. That way can be beneficial for other people looking for this feature.
Best,
Thanks.

**Comment by ota-meshi** [comment]
I don't quite understand your suggested rule. Could you please provide a detailed specification of how the rules work?

**Comment by turturmurmur** [comment]
@ota-meshi , I believe I can show with an example. 
![image](https://user-images.githubusercontent.com/89113207/217400363-2672c8a7-d552-422c-bbd1-66f7fd05253a.png)
In here I have a json file with the same values for different keys. In here I have created a custom function/plugin to detect the duplicate values(just like built in duplicate key detection) but I am detecting the values. And the problems part show the issue in the vscode problems panel. Let me know what you think please. The only problem is that it thinks the file is in ts whereas I am looking into json. In that area I will need your expertise.

**Comment by ota-meshi** [comment]
Why disallow duplicate values from JSON?
If you want to forbid in some definition JSON files, I think it makes sense to use [JSON Schema](https://json-schema.org/).

Also, I have published a plugin for checking JSON/YAML/TOML using JSON Schema.
https://github.com/ota-meshi/eslint-plugin-json-schema-validator

My current thinking is that I don't need your suggested rule.

**Comment by turturmurmur** [comment]
Here's why, imagine there are multiple people working in the same JSON file. Where they are manually adding the same values over and over again in the JSON file. This rule is to enforce no human errors happen like this. Because the file is getting bigger each time due to duplication. 
This happens a lot with QAs when they are using a file to read test data.
It is not about blocking a data type so JSON schema would not do it. It is about blocking the same values to be added with different keys.

**Comment by ota-meshi** [comment]
I'm not sure what format of JSON file you are talking about. For example I think package.json should allow duplicate values.v

**Comment by turturmurmur** [comment]
I am not talking about package.json. I am talking about test data. where QAs will pull that data to feed it to their automation tests. 
This rule should be excluding any other folder than the desired folder as well. 
Think of .env files. QAs will use .json files to keep their data where they by accident create duplicate values and create problems.

**Comment by ota-meshi** [comment]
Is it a common file format? I don't want to add rules to this plugin just to check your own test data you use.
I think it makes sense for you to create your own plugin to implement your wanted rules (as you are already doing).

**Comment by turturmurmur** [comment]
It was just a suggestion. Yes, it is a very common practice. Every big company will have it. They just get it written by their engs, but I understand you as well. Your repo is common, if I publish it I won't be found as I do not want to put time into documentation.

**Comment by ota-meshi** [comment]
> Yes, it is a very common practice.

Could you provide a document describing that format?

**Comment by turturmurmur** [comment]
Yes, of course. It is a simple .json file where the test data is stored at.
Here's a couple screenshots of it from a single framework. 
![image](https://user-images.githubusercontent.com/89113207/217974843-f8d5b243-64b8-4ebf-a048-b248b14a157b.png)
![image](https://user-images.githubusercontent.com/89113207/217974890-692e724a-e17e-4a7c-80bd-0ec7b2838725.png)
I have taken these images from this resource [here](https://dzone.com/articles/configure-cypress-tests-to-run-on-multiple-environments).
The same json usage happens for selenium, puppeteer, playwright, spec flow, and so on. 

The only difference between these pictures is, in a big project, you will have tens of other people adding hundreds of lines to these env files. In the end you will have over 1000 lines in these json files where people make the mistake and add the same value with a different key.
That should help a lot of people.

**Comment by ota-meshi** [comment]
I don't understand why disallowing different keys from having the same value in the environment file would solve the problem.
It seemed to me that it would just suffer from many false positives.

**Comment by turturmurmur** [comment]
The aim is to have those positives because there is always someone who does not care and creates the same value with a different key.
For example,
I have the json below
 "url": "base.com",
"userX" : "xyz@hotmail.com",
.
.
.
.
"urlA": "base.com"

This happens frequently. Then file has all these arbitrary values.
And lets say my url changes, then I have to change the same url in 7 different places because someone tried to duplicate the value.
The whole idea is to reuse the data, not duplicate it.
