### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by gernotpokorny** [ota-meshi/eslint-plugin-jsonc#237]
I provided a [Testrepo ](https://github.com/gernotpokorny/eslint-testrepo-codeaction-failed)where it is pretty easy to reproduce this error within the Output of Eslint within Visual Studio Code.

1. `npm i`
2. Open `foo.json`
3. Go to the Eslint Output within Visual Studio Code

That's it.

```
[Info  - 1:13:01 AM] ESLint server is starting.
[Info  - 1:13:02 AM] ESLint server running in node v16.17.1
[Info  - 1:13:02 AM] ESLint server is running.
[Info  - 1:13:04 AM] ESLint library loaded from: C:\Home\tmp\eslint\node_modules\eslint\lib\api.js
[Error - 1:13:12 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-next-line/: Nothing to repeat
  Code: -32603 
```

What is the reason for this error?

I cannot find any regular expression that looks like the one within the error message, not even within `node_modules`.

**Comment by ota-meshi** [comment]
It seems to be an issue with VSCode ESLint.
https://github.com/microsoft/vscode-eslint/issues/1610
But it's already fixed but not released yet.
I can't do anything with this repository so I'm closing the issue.
