### ISSUE TITLE
vscode-eslint extension cannot validate JSON using the "eslint.probe" configuration

### ISSUE THREAD

**Issue by ccnnde** [ota-meshi/eslint-plugin-jsonc#248]
The following content is from the setting options of [vscode-eslint](https://github.com/microsoft/vscode-eslint#settings-options)

> - `eslint.probe` - an array for language identifiers for which the ESLint extension should be activated and should try to validate the file. If validation fails for probed languages the extension says silent. Defaults to `["javascript", "javascriptreact", "typescript", "typescriptreact", "html", "vue", "markdown"]`.
> - `eslint.validate` - an array of language identifiers specifying the files for which validation is to be enforced. This is an old legacy setting and should in normal cases not be necessary anymore. Defaults to `["javascript", "javascriptreact"]`.

I can only use `"eslint.validate": ["json"]` in my settings.json for the validation to take effect.

**Comment by ota-meshi** [comment]
Please see https://ota-meshi.github.io/eslint-plugin-jsonc/user-guide/#editor-integrations

**Comment by wonsuc** [comment]
I wonder why it works for me. I added `"eslint.probe": [ ..., "json" ]` and everything works perfectly. Has something changed?

**Comment by wonsuc** [comment]
Okay, I noticed I was using pre-released version of `vscode-eslint` which is `v3.0.5`. On current stable version only supports `"eslint.validate"` option.

**Comment by wonsuc** [comment]
`"eslint.experimental.useFlatConfig"` option name also changed to `"eslint.useFlatConfig"` on `v3.0.5`. It would be better describes these things in the docs.
