### ISSUE TITLE
Get eslint-plugin-jsonc version via command line

### ISSUE THREAD

**Issue by nvuillam** [ota-meshi/eslint-plugin-jsonc#30]
I need a way to get eslint-plugin-jsonc version from command line to generate correct information is [eslint-plugin-jsonc page on Mega-Linter](https://nvuillam.github.io/mega-linter/descriptors/json_eslint_plugin_jsonc/). Currently i'm just able to retrieve eslint version.

Is it existing ? :)

Thanks !

**Comment by ota-meshi** [comment]
Thank you for question.
This plugin is not used directly from the CLI, so there are no commands.
If you have a mechanism to get the version of `@typescript-eslint/eslint-plugin` from the CLI, I think you can get the version of this plugin in the same way.

**Comment by nvuillam** [comment]
Solved by https://github.com/eslint/eslint/issues/14031 :)

`npm list eslint-plugin-jsonc` :)
