### ISSUE TITLE
Autofix for jsonc/sort-keys doesn't fix in 1 iteration

### ISSUE THREAD

**Issue by abejfehr** [ota-meshi/eslint-plugin-jsonc#355]
I have very large translation files that should be alphabetized according to the `jsonc/sort-keys` rule, but they autofix doesn't work in 1 iteration.

For a particularly large JSON file, it takes hitting save _many_ times before the file is finally in the order it needs to be in.

Here's a minimal-ish sample: 

```
{
  "i::b::c": "",
  "i::a::l": "",
  "i::d::h": "",
  "i::d::l": "",
  "i::ap::mwd": "",
  "i::b::cc": "",
  "a::c::h::c": "",
  "a::c::h::e": "",
  "i::b::caj": "",
  "i::b::cac": "",
  "i::ap::av::l": "",
  "i::ap::mw::la": "",
  "a::c::pc::u": "",
  "a::c::pe::u": "",
  "a::c::vfi::u": ""
}
```

For the above file to be alphabetized, I have to hit save (which runs autofix) twice. 

https://github.com/user-attachments/assets/14a69ac1-28e2-45a2-864e-8cb251de7034

**Comment by ota-meshi** [comment]
That's a limitation of ESLint.
If your code requires many fixes, you may need to run autofixes multiple times.

**Comment by abejfehr** [comment]
What limitation is that exactly? Do you have a link to their docs?

**Comment by jaketodaro** [comment]
@ota-meshi I don't think this is an issue with having multiple fixes. If you have a large file with hundreds of keys and just one item is not sorted correctly, applying the autofix will move the unsorted item closer to the correct spot but not all the way. I have a file in my repo that can sometimes take 10 auto fix runs to finally get the unsorted item in the correct spot.
