### ISSUE TITLE
ESLint 9 compatible release

### ISSUE THREAD

**Issue by AlCalzone** [ota-meshi/eslint-plugin-jsonc#362]
Hi @ota-meshi, would it be possible to get a new release with ESLint 9 / typescript-eslint 8 compatibility, now that https://github.com/ota-meshi/eslint-plugin-jsonc/pull/351 is merged?

Anything that needs help before a release can be made?

**Comment by ota-meshi** [comment]
I think it already supports ESLint v9. The typescript syntax has nothing to do with the JSON syntax.

**Comment by AlCalzone** [comment]
I might have missed the release then. When I tried upgrading to ESLint 9 and flat config, I was getting build errors for rules I built using this plugin. Will try again and report back.

**Comment by AlCalzone** [comment]
It works now indeed. Thanks for confirming!
