### ISSUE TITLE
 Error while loading rule 'jsonc/no-irregular-whitespace': Cannot read properties of undefined (reading 'skipComments')

### ISSUE THREAD

**Issue by Holiden** [ota-meshi/eslint-plugin-jsonc#376]
After updating eslint to 9.15.0, I get the following error:

```
Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule 'jsonc/no-irregular-whitespace': Cannot read properties of undefined (reading 'skipComments')
```

Relates to https://github.com/eslint/eslint/issues/19134

**Comment by ota-meshi** [comment]
It seems to work fine in the test cases in this repository.
Can you provide a repository where we can reproduce your problem?

**Comment by Holiden** [comment]
Yes, of course, [here minimal repro](https://github.com/Holiden/repro-jsonc)

**Comment by ota-meshi** [comment]
Thanks, I fixed the issue.
