### ISSUE TITLE
Doesn't work with a different parser/AST

### ISSUE THREAD

**Issue by GitGangGuy** [ota-meshi/eslint-plugin-jsonc#92]
I'm using [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) in my project so ESLint understands the experimental JavaScript syntax I write. It uses a different AST. When pairing it with your plugin (`eslint-plugin-jsonc`), ESLint fails to parse my json files. See my [reproduction](https://github.com/GitGangGuy/issue-eslint-jsonc). Can you fix this? :smile:

**Comment by ota-meshi** [comment]
Thank you for posting this issue!

It looks like you need to add an overrides section.

```js
    "overrides": [
        {
            "files": ["*.json", "*.json5"],
            "parser": "jsonc-eslint-parser",
        }
    ]
```

The [`base` configuration](https://github.com/ota-meshi/eslint-plugin-jsonc/blob/master/lib/configs/base.ts#L6) provided by this plugin will try to enable this setting.
However, the user's parser setting has a higher priority than the "extends" parser by extension, and it seems that the parser by extension is not used.

I will add to the documentation about this workaround.
