### ISSUE TITLE
jsonc/sort-key not worked as expected ?

### ISSUE THREAD

**Issue by davidNHK** [ota-meshi/eslint-plugin-jsonc#96]
Reproduce:
Move any key in package.json to random order

```js
checkout https://github.com/davidNHK/busybox
yarn
./node_modules/.bin/eslint ./package.json 
```

expected : 
eslint report error and --fix can auto resort 

actual:
no error

My config here:
https://github.com/davidNHK/busybox/blob/development/packages/eslint-config/preset/base.js#L84

**Comment by davidNHK** [comment]
More info

https://github.com/ota-meshi/eslint-plugin-jsonc/blob/master/lib/rules/sort-keys.ts#L297

I try add logging here, the `parserServices` always undefined

**Comment by ota-meshi** [comment]
You need to change the presets you use.

```diff
-      extends: ['plugin:jsonc/prettier'],
+      extends: ['plugin:jsonc/base'],
```

**Comment by davidNHK** [comment]
@ota-meshi i tried what you suggested , but no luck

**Comment by davidNHK** [comment]
turn out i find it has conflict between my eslint config , thanks @ota-meshi for support 

You did a great job to make our life more efficient !

**Comment by davidNHK** [comment]
for fork who hit exact problem to me .

Here is some situation on my eslint config
i have shared eslint config which aim to support `react`, `typescript`, `js` in one js config

and my `ts` eslint config look like that 

```js
const { overrides } = require('./base');

const jsConfig = overrides.find(override => override.files.includes('*.js'));

module.exports = {
  overrides: [
    {
      extends: [
        ...jsConfig.extends,
        'plugin:@typescript-eslint/recommended',
        'plugin:import/typescript',
        'plugin:typescript-sort-keys/recommended',
      ],
      files: ['*.ts', '*.tsx'],
      parser: '@typescript-eslint/parser',
      rules: {
       // ....some ts rule here
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint/eslint-plugin', 'typescript-sort-keys'],
  settings: {
    'import/resolver': {
      typescript: {},
    },
  },
};
```

i have put parser in top level of my json.

and seem it cause conflict between `json` parser used here.

i have attempt add `parser` options on `.json` but no luck.

and turn out i change my ts eslint like that

```
const { overrides } = require('./base');

const jsConfig = overrides.find(override => override.files.includes('*.js'));

module.exports = {
  overrides: [
    {
      extends: [
        ...jsConfig.extends,
        'plugin:@typescript-eslint/recommended',
        'plugin:import/typescript',
        'plugin:typescript-sort-keys/recommended',
      ],
      parser: '@typescript-eslint/parser',
      plugins: ['@typescript-eslint/eslint-plugin', 'typescript-sort-keys'],
      files: ['*.ts', '*.tsx'],
      parser: '@typescript-eslint/parser',
      rules: {
       // ....some ts rule here
      },
    },
  ],
  settings: {
    'import/resolver': {
      typescript: {},
    },
  },
};
```
